title: Oshomo Oforomeh
email: hello@oshomo.oforomeh.com
twitter_username: hoshomoh
github_username:  oshomo

# Build settings
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed
